// ==================================================================
// BMG — OBJECTIVE-КАРТЫ ДЛЯ БИЛДЕРА КОЛОДЫ ЦЕЛЕЙ
// ==================================================================

const OBJECTIVE_DECK = { size: 30, maxGeneral: 15, maxSingle: 15 };

const OBJECTIVE_CARDS = [
  { id:"character-reinforce-bird", name:"REINFORCE", img:"img/cards/characters/reinforce-bird.jpg", vp:2, max:1, reqModel:["Bird", "Bird (Classic)"], reqRank:["Sidekick"] },
  { id:"character-im-the-surgeon", name:"I'M THE SURGEON", img:"img/cards/characters/im-the-surgeon.jpg", vp:2, max:1, reqModel:["Batman (Frank Miller)", "Batman (Frank Miller on Horse)", "Batman (Frank Miller on Power Armor)"], reqRank:["Leader"] },
  { id:"character-lord-of-the-pits", name:"LORD OF THE PITS", img:"img/cards/characters/lord-of-the-pits.jpg", vp:2, max:1, reqModel:["Ra's Al Ghul", "Ra's Al Ghul (Rebirth)"], reqRank:["Leader"] },
  { id:"character-masters-duel", name:"MASTER'S DUEL", img:"img/cards/characters/masters-duel.jpg", vp:2, max:1, reqModel:["Lady Shiva"], reqRank:["Sidekick"] },
  { id:"character-seeking-revenge", name:"SEEKING REVENGE", img:"img/cards/characters/seeking-revenge.jpg", vp:2, max:1, reqModel:["Arkham Knight", "Red Hood (Arkham Knight)", "Robin", "Red Hood (Rebirth)", "Red Hood (The Outlaw)"], reqRank:["Free Agent"] },
  { id:"character-regrowth", name:"REGROWTH", img:"img/cards/characters/regrowth.jpg", vp:2, max:1, reqModel:["Poison Ivy", "Poison Ivy (1997)"], reqRank:["Leader", "Sidekick"] },
  { id:"character-feed-me", name:"FEED ME", img:"img/cards/characters/feed-me.jpg", vp:2, max:1, reqModel:["Frank the Plant"], reqRank:["Henchman"] },
  { id:"character-kataykuchi", name:"KATAYKUCHI", img:"img/cards/characters/kataykuchi.jpg", vp:2, max:1, reqModel:["Katana", "Katana (Suicide Squad)", "Katana (Rebirth)"], reqRank:["Free Agent"] },
  { id:"character-netmaster", name:"NETMASTER", img:"img/cards/characters/netmaster.jpg", vp:3, max:1, reqModel:["Oracle"], reqRank:["Sidekick", "Free Agent"] },
  { id:"character-a-cat-has-its-needs", name:"A CAT HAS ITS NEEDS", img:"img/cards/characters/a-cat-has-its-needs.jpg", vp:2, max:1, reqModel:["Catwoman", "Catwoman (Modern Age)", "Catwoman (Dark Knight Rises)", "Catwoman (Julie Newmar)", "Catwoman (Zoë Kravitz)", "Catwoman (Michelle Pfeiffer)", "Catwoman (The Animated Series)"], reqRank:["Free Agent"] },
  { id:"character-justice", name:"JUSTICE", img:"img/cards/characters/justice.jpg", vp:2, max:1, reqModel:["Two-Face", "Two-Face (Dark Knight)", "Two-Face (Arkham City)", "Two-Face (Tommy Lee Jones)"], reqRank:["Leader"] },
  { id:"character-riddles-everywhere", name:"RIDDLES EVERYWHERE", img:"img/cards/characters/riddles-everywhere.jpg", vp:2, max:2, reqModel:["The Riddler (Arkham Knight)", "The Riddler (Modern Age)", "The Riddler", "The Riddler (Paul Dano)", "The Riddler (Frank Gorshin)", "The Riddler (Jim Carrey)"], reqRank:["Leader"] },
  { id:"character-diversion-tactic", name:"DIVERSION TACTIC", img:"img/cards/characters/diversion-tactic.jpg", vp:2, max:2, reqModel:["Quelle"], reqRank:["Sidekick"] },
  { id:"character-query-and-echo", name:"QUERY AND ECHO", img:"img/cards/characters/query-and-echo.jpg", vp:2, max:1, reqModel:["Query"], reqRank:["Henchman"] },
  { id:"character-echo-and-query", name:"ECHO AND QUERY", img:"img/cards/characters/echo-and-query.jpg", vp:2, max:1, reqModel:["Echo"], reqRank:["Henchman"] },
  { id:"character-this-ends-tonight", name:"THIS ENDS TONIGHT", img:"img/cards/characters/this-ends-tonight.jpg", vp:2, max:1, reqModel:["Arkham Knight"], reqRank:["Leader"] },
  { id:"character-a-city-in-fear", name:"A CITY IN FEAR", img:"img/cards/characters/a-city-in-fear.jpg", vp:2, max:1, reqModel:["Scarecrow (Arkham Knight)", "Scarecrow", "Scarecrow (Arkham Asylum)", "Scarecrow (The Worst Nightmare)"], reqRank:["Leader", "Sidekick"] },
  { id:"character-my-house-my-rules", name:"MY HOUSE, MY RULES", img:"img/cards/characters/my-house-my-rules.jpg", vp:2, max:1, reqModel:["The Penguin (New 52)", "The Penguin (Arkham Knight)", "The Penguin (Colin Farrell)", "The Penguin (Arkham City)", "The Penguin (Danny DeVito)", "The Penguin (Burgess Meredith)", "The Penguin (Penguin's Duck)"], reqRank:["Leader"] },
  { id:"character-endless-greed", name:"ENDLESS GREED", img:"img/cards/characters/endless-greed.jpg", vp:3, max:1, reqModel:["Emperor Penguin", "Emperor Penguin (Unchained)"], reqRank:["Leader"] },
  { id:"character-street-transaction", name:"STREET TRANSACTION", img:"img/cards/characters/street-transaction.jpg", vp:2, max:1, reqModel:["Loose Lips"], reqRank:["Sidekick"] },
  { id:"character-plots-behind-plots", name:"PLOTS BEHIND PLOTS", img:"img/cards/characters/plots-behind-plots.jpg", faction:["Court of Owls"], vp:3, max:1, reqModel:["Lincoln March"], reqRank:["Leader", "Henchman"] },
  { id:"character-the-courts-edict", name:"THE COURT'S EDICT", img:"img/cards/characters/the-courts-edict.jpg", vp:3, max:1, reqModel:["The Court"], reqRank:["Leader"] },
  { id:"character-the-mission", name:"THE MISSION", img:"img/cards/characters/the-mission.jpg", vp:2, max:1, reqModel:["The Talon"], reqRank:["Henchman"] },
  { id:"character-escape-plan", name:"ESCAPE PLAN", img:"img/cards/characters/escape-plan.jpg", vp:3, max:1, reqModel:["Talon"], reqRank:["Free Agent"] },
  { id:"character-osito", name:"OSITO", img:"img/cards/characters/osito.jpg", vp:2, max:1, reqModel:["Bane (Dark Knight Rises)", "Bane (Rebirth)", "Bane (The Bat)", "Bane (Unleashed)", "Bane (Titan)", "Bane (Commander)"], reqRank:["Leader"] },
  { id:"character-emancipation", name:"EMANCIPATION", img:"img/cards/characters/emancipation.jpg", vp:2, max:1, reqModel:["Harley Quinn (Arkham Knight)", "Harley Quinn (Rebirth)", "Harley Quinn (Suicide Squad)", "Harley Quinn", "Harley Quinn (Bombshell)", "Harley Quinn (BTG)", "Harley Quinn (Bewitched)", "Harley Quinn (The Suicide Squad)", "Harley Quinn (Roller Derby)", "Harley Quinn (Arkham Asylum)", "Harley Quinn (& the Boys)"], reqRank:["Free Agent"] },
  { id:"character-cover-your-ears", name:"COVER YOUR EARS", img:"img/cards/characters/cover-your-ears.jpg", vp:2, max:1, reqModel:["Black Canary", "Black Canary (Rebirth)", "Black Canary (The Animated Series)"], reqRank:["Sidekick", "Free Agent", "Henchman"] },
  { id:"character-vendetta", name:"VENDETTA", img:"img/cards/characters/vendetta.jpg", vp:2, max:1, reqModel:["Huntress", "Huntress (Classic)"], reqRank:["Henchman"] },
  { id:"character-gotham-is-mine", name:"GOTHAM IS MINE", img:"img/cards/characters/gotham-is-mine.jpg", vp:3, max:1, reqModel:["Bane (The Bat)"], reqRank:["Leader"] },
  { id:"character-corrupted", name:"CORRUPTED", img:"img/cards/characters/corrupted.jpg", vp:1, max:3, reqModel:["The Batman Who Laughs"], reqRank:["Free Agent"] },
  { id:"character-apex-predator", name:"APEX PREDATOR", img:"img/cards/characters/apex-predator.jpg", vp:2, max:3, reqModel:["The Batman Who Laughs"], reqRank:["Free Agent"] },
  { id:"character-showtime", name:"SHOWTIME!", img:"img/cards/characters/showtime.jpg", vp:2, max:1, reqModel:["Joker", "Joker (Arkham Asylum)", "Joker (Jared Leto)", "Joker (Dark Knight Rises)", "Joker (The Killing Joke)", "Joker (Red Hood)", "Joker (Cesar Romero)", "Joker (The Criminal)", "Joker (Titan)", "Joker (Christmas)", "Joker (Having Fun)", "Joker (Explosive Arrival)"], reqRank:["Leader"] },
  { id:"character-joker-o-meter", name:"JOKER-O-METER", img:"img/cards/characters/joker-o-meter.jpg", vp:2, max:1, reqModel:["Harley Quinn (Arkham Knight)", "Harley Quinn (Rebirth)", "Harley Quinn (Suicide Squad)", "Harley Quinn", "Harley Quinn (Bombshell)", "Harley Quinn (BTG)", "Harley Quinn (Bewitched)", "Harley Quinn (The Suicide Squad)", "Harley Quinn (Roller Derby)", "Harley Quinn (Arkham Asylum)", "Harley Quinn (& the Boys)"], reqRank:["Sidekick"] },
  { id:"character-one-million-dollar-shot", name:"ONE MILLION DOLLAR SHOT", img:"img/cards/characters/one-million-dollar-shot.jpg", vp:2, max:1, reqModel:["Deadshot (Classic)", "Deadshot (Suicide Squad)", "Deadshot"], reqRank:["Free Agent"] },
  { id:"character-wrong-place-kid", name:"WRONG PLACE, KID", img:"img/cards/characters/wrong-place-kid.jpg", vp:2, max:1, reqModel:["Sgt. Harvey Bullock"], reqRank:["Henchman"] },
  { id:"character-back-to-arkham", name:"BACK TO ARKHAM", img:"img/cards/characters/back-to-arkham.jpg", vp:2, max:1, reqModel:["Batman", "Batman (Arkham Knight)", "Batman (Ben Affleck)", "Batman (Modern Age)", "Batman (Dark Knight Rises)", "Zur-En-Arrh Batman", "Batman (Rebirth)", "The Batman Who Laughs", "The Red Death", "The Merciless", "Batman (Knightmare)", "Batman (Multiverse)", "Batman (Gaslight)", "Bruce Wayne", "Batman (Frank Miller)", "The Grim Knight", "Batman (Adam West)", "Batman (Year One)", "Batman (Red Rain)", "Batman (Death Metal)", "Batman (Viking)", "Batman (Robert Pattinson)", "The Drifter (Robert Pattinson)", "Batman (Classic)", "Batman on Bike (Robert Pattinson)", "Batman (The Cult)", "Batman (Bushi)", "Batman (Michael Keaton)", "Batman (1997)", "Batman (High Seas)", "Batman (Frank Miller on Horse)", "Batman (Frank Miller on Power Armor)", "Mr. Wayne (Beyond)", "Batman (The Animated Series)"], reqRank:["Leader"] },
  { id:"character-one-good-cop", name:"ONE GOOD COP", img:"img/cards/characters/one-good-cop.jpg", vp:2, max:1, reqModel:["Commissioner Gordon", "Lieutenant Gordon (Year One)", "Lt. Gordon (Jeffrey Wright)"], reqRank:["Leader"] },
  { id:"character-daughter-of-the-demon", name:"DAUGHTER OF THE DEMON", img:"img/cards/characters/daughter-of-the-demon.jpg", vp:2, max:1, reqModel:["Talia Al Ghul", "Talia (Rebirth)", "Miranda Tate"], reqRank:["Leader", "Sidekick"] },
  { id:"character-my-life-for-the-league", name:"MY LIFE FOR THE LEAGUE", img:"img/cards/characters/my-life-for-the-league.jpg", vp:2, max:1, reqModel:["The Heretic"], reqRank:["Sidekick"] },
  { id:"character-mortal-wound", name:"MORTAL WOUND", img:"img/cards/characters/mortal-wound.jpg", vp:2, max:3, reqModel:["Cheshire"], reqRank:["Free Agent"] },
  { id:"character-searching-for-nora", name:"SEARCHING FOR NORA", img:"img/cards/characters/searching-for-nora.jpg", faction:["Mr. Freeze"], vp:2, max:1, reqModel:["Mr. Freeze (Arkham Knight)", "Mr. Freeze (Cryo-Armor)", "Mr. Freeze (1997)"], reqRank:["Leader"], prevTrait:["A Lot Colder"] },
  { id:"character-cold-as-ice", name:"COLD AS ICE", img:"img/cards/characters/cold-as-ice.jpg", faction:["Mr. Freeze"], vp:2, max:1, reqModel:["Killer Frost", "Killer Frost (Rebirth)"], reqRank:["Sidekick"] },
  { id:"character-the-don", name:"THE DON", img:"img/cards/characters/the-don.jpg", vp:2, max:1, reqModel:["The Roman", "Carmine Falcone (John Turturro)"], reqRank:["Leader"] },
  { id:"character-uncontrolled-brutality", name:"UNCONTROLLED BRUTALITY", img:"img/cards/characters/uncontrolled-brutality.jpg", vp:2, max:1, reqModel:["Sal Maroni"], reqRank:["Leader"] },
  { id:"character-the-true-boss", name:"THE TRUE BOSS", img:"img/cards/characters/the-true-boss.jpg", vp:2, max:1, reqModel:["The Ventriloquist"], reqRank:["Leader"] },
  { id:"character-pain-and-money", name:"PAIN AND MONEY", img:"img/cards/characters/pain-and-money.jpg", vp:2, max:2, reqModel:["Black Mask"], reqRank:["Leader"] },
  { id:"character-not-so-much-sugar", name:"NOT SO MUCH SUGAR", img:"img/cards/characters/not-so-much-sugar.jpg", vp:2, max:1, reqModel:["Sugar"], reqRank:["Sidekick"] },
  { id:"character-spice-it-a-little", name:"SPICE IT A LITTLE", img:"img/cards/characters/spice-it-a-little.jpg", vp:2, max:1, reqModel:["Spice"], reqRank:["Sidekick"] },
  { id:"character-master-of-manipulation", name:"MASTER OF MANIPULATION", img:"img/cards/characters/master-of-manipulation.jpg", vp:3, max:1, reqModel:["Hush"], reqRank:["Free Agent"] },
  { id:"character-yours-to-command", name:"YOURS TO COMMAND", img:"img/cards/characters/yours-to-command.jpg", vp:2, max:1, reqModel:["Ubu"], reqRank:["Henchman"] },
  { id:"character-great-performance", name:"GREAT PERFORMANCE", img:"img/cards/characters/great-performance.jpg", vp:4, max:1, reqModel:["Nightwing (Arkham Knight)", "Nightwing", "Nightwing (Rebirth)"], reqRank:["Sidekick", "Free Agent"] },
  { id:"character-assistance", name:"ASSISTANCE", img:"img/cards/characters/assistance.jpg", vp:2, max:2, reqModel:["Robin (Boy Wonder)", "Robin", "Robin (Teen Titans)", "Robin (Burt Ward)", "Robin (Classic)", "Robin (1997)", "Robin (Beyond)", "Robin (Tim Drake)"], reqRank:["Sidekick", "Free Agent", "Henchman"] },
  { id:"character-trick-shot", name:"TRICK SHOT", img:"img/cards/characters/trick-shot.jpg", vp:2, max:2, reqModel:["Green Arrow", "Green Arrow (Rebirth)", "Green Arrow (The Animated Series)"], reqRank:["Sidekick"] },
  { id:"character-justice-served", name:"JUSTICE SERVED", img:"img/cards/characters/justice-served.jpg", vp:3, max:1, reqModel:["Peacemaker (John Cena)"], reqRank:["Sidekick", "Free Agent"] },
  { id:"character-best-served-cold", name:"BEST SERVED COLD", img:"img/cards/characters/best-served-cold.jpg", vp:2, max:2, reqModel:["Mrs. Freeze"], reqRank:["Sidekick"] },
  { id:"character-bigger-picture", name:"BIGGER PICTURE", img:"img/cards/characters/bigger-picture.jpg", vp:2, max:2, reqModel:["The Riddler (Paul Dano)"], reqRank:["Leader"] },
  { id:"character-freelance-assassin", name:"FREELANCE ASSASSIN", img:"img/cards/characters/freelance-assassin.jpg", vp:4, max:1, reqModel:["Raptor"], reqRank:["Free Agent"] },
  { id:"character-vengeances-mission", name:"VENGEANCE'S MISSION", img:"img/cards/characters/vengeances-mission.jpg", vp:2, max:1, reqModel:["Vengeance"], reqRank:["Leader"] },
  { id:"character-sewers-nightmare", name:"SEWER'S NIGHTMARE", img:"img/cards/characters/sewers-nightmare.jpg", vp:2, max:3, reqModel:["Killer Croc (Suicide Squad)", "Killer Croc", "Killer Croc (Arkham Asylum)", "Killer Croc (Thug)"], reqRank:["Free Agent"] },
  { id:"character-the-best-act", name:"THE BEST ACT", img:"img/cards/characters/the-best-act.jpg", vp:2, max:2, reqModel:["Clayface"], reqRank:["Free Agent"] },
  { id:"character-primary-instincts", name:"PRIMARY INSTINCTS", img:"img/cards/characters/primary-instincts.jpg", vp:2, max:1, reqModel:["Man-Bat"], reqRank:["Free Agent"] },
  { id:"character-born-on-a-monday", name:"BORN ON A MONDAY", img:"img/cards/characters/born-on-a-monday.jpg", vp:2, max:1, reqModel:["Solomon Grundy"], reqRank:["Free Agent"] },
  { id:"character-tally-marks", name:"TALLY MARKS", img:"img/cards/characters/tally-marks.jpg", vp:3, max:1, reqModel:["Victor Zsasz"], reqRank:["Free Agent"] },
  { id:"character-this-is-the-evil", name:"THIS IS THE EVIL", img:"img/cards/characters/this-is-the-evil.jpg", vp:2, max:3, reqModel:["Deacon Blackfire"], reqRank:["Leader"] },
  { id:"character-join-the-fold", name:"JOIN THE FOLD", img:"img/cards/characters/join-the-fold.jpg", faction:["Cults"], vp:2, max:1, reqModel:["Young Woman"], reqRank:["Henchman"] },
  { id:"character-the-unworthy", name:"THE UNWORTHY", img:"img/cards/characters/the-unworthy.jpg", vp:2, max:1, reqModel:["Jake"], reqRank:["Sidekick"] },
  { id:"character-the-evidence-mounts", name:"THE EVIDENCE MOUNTS", img:"img/cards/characters/the-evidence-mounts.jpg", vp:3, max:1, reqModel:["Batman (Robert Pattinson)", "Batman on Bike (Robert Pattinson)"], reqRank:["Leader"] },
  { id:"character-mother-of-strays", name:"MOTHER OF STRAYS", img:"img/cards/characters/mother-of-strays.jpg", vp:2, max:1, reqModel:["Catwoman (Zoë Kravitz)"], reqRank:["Free Agent"] },
  { id:"character-secure-the-drop", name:"SECURE THE DROP", img:"img/cards/characters/secure-the-drop.jpg", vp:2, max:1, reqModel:["The Penguin (Colin Farrell)"], reqRank:["Sidekick"] },
  { id:"character-cover-up", name:"COVER UP", img:"img/cards/characters/cover-up.jpg", vp:2, max:1, reqModel:["Carmine Falcone (John Turturro)"], reqRank:["Leader"] },
  { id:"character-moth-signal", name:"MOTH SIGNAL", img:"img/cards/characters/moth-signal.jpg", vp:2, max:1, reqModel:["Killer Moth"], reqRank:["Henchman"] },
  { id:"character-overwhelming-charisma", name:"OVERWHELMING CHARISMA", img:"img/cards/characters/overwhelming-charisma.jpg", vp:3, max:1, reqModel:["Kite-Man"], reqRank:["Henchman"] },
  { id:"character-time-master", name:"TIME MASTER", img:"img/cards/characters/time-master.jpg", vp:2, max:1, reqModel:["Clock King"], reqRank:["Free Agent"] },
  { id:"character-cold-as-death", name:"COLD AS DEATH", img:"img/cards/characters/cold-as-death.jpg", vp:2, max:1, reqModel:["Gentleman Ghost"], reqRank:["Free Agent"] },
  { id:"character-calendar-crimes", name:"CALENDAR CRIMES", img:"img/cards/characters/calendar-crimes.jpg", vp:2, max:1, reqModel:["Calendar Man"], reqRank:["Henchman"] },
  { id:"character-sauce-and-pickles", name:"SAUCE AND PICKLES", img:"img/cards/characters/sauce-and-pickles.jpg", vp:2, max:1, reqModel:["Condiment King"], reqRank:["Henchman"] },
  { id:"character-kobra-viral-bomb", name:"KOBRA VIRAL BOMB", img:"img/cards/characters/kobra-viral-bomb.jpg", vp:3, max:1, reqModel:["Kobra"], reqRank:["Leader"] },
  { id:"character-strict-control", name:"STRICT CONTROL", img:"img/cards/characters/strict-control.jpg", vp:2, max:1, reqModel:["Lady Eve"], reqRank:["Sidekick"] },
  { id:"character-state-of-fear", name:"STATE OF FEAR", img:"img/cards/characters/state-of-fear.jpg", vp:2, max:1, reqModel:["Scarecrow (Arkham Knight)", "Scarecrow", "Scarecrow (Arkham Asylum)", "Scarecrow (The Worst Nightmare)"], reqRank:["Leader"] },
  { id:"character-new-compound", name:"NEW COMPOUND", img:"img/cards/characters/new-compound.jpg", vp:2, max:2, reqModel:["Dr. Friitawa"], reqRank:["Sidekick"] },
  { id:"character-deduction", name:"DEDUCTION", img:"img/cards/characters/deduction.jpg", vp:2, max:1, reqModel:["Dr. Hugo Strange"], reqRank:["Free Agent"] },
  { id:"valuable-commodities", name:"VALUABLE COMMODITIES", img:"img/cards/valuable-commodities.jpg", vp:2, max:1, general:true },
  { id:"catch-a-bullet", name:"CATCH A BULLET", img:"img/cards/catch-a-bullet.jpg", vp:1, max:1, general:true },
  { id:"call-an-ambulance", name:"CALL AN AMBULANCE!", img:"img/cards/call-an-ambulance.jpg", vp:1, max:1, general:true },
  { id:"dirty-job", name:"DIRTY JOB", img:"img/cards/dirty-job.jpg", vp:1, max:3, general:true },
  { id:"they-must-know-pain", name:"THEY MUST KNOW PAIN", img:"img/cards/they-must-know-pain.jpg", vp:1, max:1, general:true },
  { id:"confusion", name:"CONFUSION", img:"img/cards/confusion.jpg", vp:1, max:1, general:true },
  { id:"im-feeling-weird", name:"I'M FEELING... WEIRD", img:"img/cards/im-feeling-weird.jpg", vp:1, max:2, general:true },
  { id:"stick-to-the-plan", name:"STICK TO THE PLAN", img:"img/cards/stick-to-the-plan.jpg", vp:1, max:2, general:true },
  { id:"overdrive", name:"OVERDRIVE", img:"img/cards/overdrive.jpg", vp:1, max:2, general:true },
  { id:"flanking", name:"FLANKING", img:"img/cards/flanking.jpg", vp:1, max:2, general:true },
  { id:"disturbance", name:"DISTURBANCE", img:"img/cards/disturbance.jpg", vp:1, max:2, general:true },
  { id:"stake-your-claim", name:"STAKE YOUR CLAIM", img:"img/cards/stake-your-claim.jpg", vp:1, max:2, general:true },
  { id:"die-hard", name:"DIE HARD", img:"img/cards/die-hard.jpg", vp:1, max:1, general:true },
  { id:"law-forces-comb-through-everything", name:"COMB THROUGH EVERYTHING", img:"img/cards/law-forces/comb-through-everything.jpg", faction:["GCPD"], vp:2, max:3 },
  { id:"law-forces-get-them-off-the-streets", name:"GET THEM OFF THE STREETS", img:"img/cards/law-forces/get-them-off-the-streets.jpg", faction:["GCPD"], vp:3, max:3 },
  { id:"law-forces-snitch", name:"SNITCH", img:"img/cards/law-forces/snitch.jpg", faction:["GCPD"], vp:2, max:3 },
  { id:"law-forces-secure-the-perimeter", name:"SECURE THE PERIMETER", img:"img/cards/law-forces/secure-the-perimeter.jpg", faction:["GCPD"], vp:2, max:3 },
  { id:"law-forces-they-wont-see-me-coming", name:"THEY WON'T SEE ME COMING", img:"img/cards/law-forces/they-wont-see-me-coming.jpg", faction:["GCPD"], vp:2, max:2 },
  { id:"law-forces-non-lethal-ammo", name:"NON-LETHAL AMMO", img:"img/cards/law-forces/non-lethal-ammo.jpg", faction:["GCPD"], vp:2, max:3 },
  { id:"law-forces-finding-a-suspect", name:"FINDING A SUSPECT", img:"img/cards/law-forces/finding-a-suspect.jpg", faction:["GCPD"], vp:2, max:2 },
  { id:"law-forces-wait-for-backup", name:"WAIT FOR BACKUP", img:"img/cards/law-forces/wait-for-backup.jpg", faction:["GCPD"], vp:2, max:2 },
  { id:"law-forces-uncovered-truth", name:"UNCOVERED TRUTH", img:"img/cards/law-forces/uncovered-truth.jpg", faction:["GCPD"], vp:3, max:3 },
  { id:"law-forces-following-the-clues", name:"FOLLOWING THE CLUES", img:"img/cards/law-forces/following-the-clues.jpg", faction:["GCPD"], vp:3, max:2 },
  { id:"law-forces-planting-evidence", name:"PLANTING EVIDENCE", img:"img/cards/law-forces/planting-evidence.jpg", faction:["GCPD"], vp:2, max:2 },
  { id:"law-forces-detective-work", name:"DETECTIVE WORK", img:"img/cards/law-forces/detective-work.jpg", faction:["GCPD"], vp:2, max:3 },
  { id:"law-forces-monitoring", name:"MONITORING", img:"img/cards/law-forces/monitoring.jpg", faction:["GCPD"], vp:2, max:3 },
  { id:"seeking-the-trail", name:"SEEKING THE TRAIL", img:"img/cards/vigilantes/seeking-the-trail.jpg", faction:["Bat Family"], vp:2, max:4 },
  { id:"solving-the-puzzle", name:"SOLVING THE PUZZLE", img:"img/cards/vigilantes/solving-the-puzzle.jpg", faction:["Bat Family"], vp:2, max:4 },
  { id:"attempt-thwarted", name:"ATTEMPT THWARTED", img:"img/cards/vigilantes/attempt-thwarted.jpg", faction:["Bat Family"], vp:2, max:3 },
  { id:"undercover-action", name:"UNDERCOVER ACTION", img:"img/cards/vigilantes/undercover-action.jpg", faction:["Bat Family"], vp:2, max:3 },
  { id:"ending-your-villany", name:"ENDING YOUR VILLANY", img:"img/cards/vigilantes/ending-your-villany.jpg", faction:["Bat Family"], vp:2, max:3 },
  { id:"secure-the-zone", name:"SECURE THE ZONE", img:"img/cards/vigilantes/secure-the-zone.jpg", faction:["Bat Family"], vp:2, max:3 },
  { id:"teamwork-action", name:"TEAMWORK ACTION", img:"img/cards/vigilantes/teamwork-action.jpg", faction:["Bat Family"], vp:2, max:3 },
  { id:"informant", name:"INFORMANT", img:"img/cards/vigilantes/informant.jpg", faction:["Bat Family"], vp:2, max:3 },
  { id:"patrol-report", name:"PATROL REPORT", img:"img/cards/vigilantes/patrol-report.jpg", faction:["Bat Family"], vp:3, max:3, reqTrait:["Bat Family"] },
  { id:"unveiling-the-truth", name:"UNVEILING THE TRUTH", img:"img/cards/vigilantes/unveiling-the-truth.jpg", faction:["Bat Family"], vp:3, max:3, reqTrait:["Bat Family"] },
  { id:"we-are-the-night", name:"WE ARE THE NIGHT", img:"img/cards/vigilantes/we-are-the-night.jpg", faction:["Bat Family"], vp:2, max:3, reqTrait:["Bat Family"] },
  { id:"none-of-you-are-safe", name:"NONE OF YOU ARE SAFE", img:"img/cards/vigilantes/none-of-you-are-safe.jpg", faction:["Bat Family"], vp:2, max:4, reqTrait:["Bat Family"] },
  { id:"closing-the-trigons-portal", name:"CLOSING THE TRIGON'S PORTAL", img:"img/cards/vigilantes/closing-the-trigons-portal.jpg", faction:["Bat Family"], vp:3, max:3, reqTrait:["Teen Titans"] },
  { id:"stubborn-resilience", name:"STUBBORN RESILIENCE", img:"img/cards/vigilantes/stubborn-resilience.jpg", faction:["Bat Family"], vp:2, max:4, reqTrait:["Teen Titans"] },
  { id:"containing-the-threat", name:"CONTAINING THE THREAT", img:"img/cards/vigilantes/containing-the-threat.jpg", faction:["Bat Family"], vp:2, max:3, reqTrait:["Teen Titans"] },
  { id:"much-to-prove", name:"MUCH TO PROVE", img:"img/cards/vigilantes/much-to-prove.jpg", faction:["Bat Family"], vp:3, max:3, reqTrait:["Teen Titans"] },
  { id:"tonight-we-are-the-law", name:"TONIGHT, WE ARE THE LAW", img:"img/cards/vigilantes/tonight-we-are-the-law.jpg", faction:["Bat Family"], vp:2, max:3, reqTrait:["Bat Family"] },
  { id:"so-long-its-been-a-gas", name:"SO LONG... IT'S BEEN A GAS!", img:"img/cards/joker/so-long-its-been-a-gas.jpg", faction:["Joker"], vp:2, max:3 },
  { id:"bite-the-dust", name:"BITE THE DUST!", img:"img/cards/joker/bite-the-dust.jpg", faction:["Joker"], vp:2, max:4 },
  { id:"let-them-in-on-the-joke", name:"LET THEM IN ON THE JOKE", img:"img/cards/joker/let-them-in-on-the-joke.jpg", faction:["Joker"], vp:2, max:3 },
  { id:"it-doesnt-look-fresh", name:"IT DOESN'T LOOK FRESH", img:"img/cards/joker/it-doesnt-look-fresh.jpg", faction:["Joker"], vp:2, max:3 },
  { id:"lets-dance", name:"LET'S DANCE!", img:"img/cards/joker/lets-dance.jpg", faction:["Joker"], vp:2, max:2 },
  { id:"youre-expendable", name:"YOU'RE EXPENDABLE", img:"img/cards/joker/youre-expendable.jpg", faction:["Joker"], vp:1, max:2 },
  { id:"seasoning-the-mix", name:"SEASONING THE MIX", img:"img/cards/joker/seasoning-the-mix.jpg", faction:["Joker"], vp:2, max:2 },
  { id:"let-them-do-their-thing", name:"LET THEM DO THEIR THING", img:"img/cards/joker/let-them-do-their-thing.jpg", faction:["Joker"], vp:2, max:2 },
  { id:"psychopaths", name:"PSYCHOPATHS", img:"img/cards/joker/psychopaths.jpg", faction:["Joker"], vp:3, max:3 },
  { id:"the-first-laugh", name:"THE FIRST LAUGH", img:"img/cards/joker/the-first-laugh.jpg", faction:["Joker"], vp:2, max:3 },
  { id:"poisoning-gotham", name:"POISONING GOTHAM", img:"img/cards/joker/poisoning-gotham.jpg", faction:["Joker"], vp:2, max:2 },
  { id:"ace-chemicals-barrel", name:"ACE CHEMICAL'S BARREL", img:"img/cards/joker/ace-chemicals-barrel.jpg", faction:["Joker"], vp:2, max:3 },
  { id:"stage-play", name:"STAGE PLAY", img:"img/cards/joker/stage-play.jpg", faction:["Joker"], vp:2, max:3 },
  { id:"search-and-destroy", name:"SEARCH & DESTROY", img:"img/cards/soldiers-of-fortune/search-and-destroy.jpg", faction:["Bane"], vp:2, max:3 },
  { id:"hardpoint", name:"HARDPOINT", img:"img/cards/soldiers-of-fortune/hardpoint.jpg", faction:["Bane"], vp:2, max:2 },
  { id:"ground-war", name:"GROUND WAR", img:"img/cards/soldiers-of-fortune/ground-war.jpg", faction:["Bane"], vp:3, max:2 },
  { id:"invasion", name:"INVASION", img:"img/cards/soldiers-of-fortune/invasion.jpg", faction:["Bane"], vp:2, max:3 },
  { id:"domination", name:"DOMINATION", img:"img/cards/soldiers-of-fortune/domination.jpg", faction:["Bane"], vp:3, max:3 },
  { id:"free-for-all", name:"FREE-FOR-ALL", img:"img/cards/soldiers-of-fortune/free-for-all.jpg", faction:["Bane"], vp:2, max:2 },
  { id:"black-ops", name:"BLACK OPS", img:"img/cards/soldiers-of-fortune/black-ops.jpg", faction:["Bane"], vp:2, max:4 },
  { id:"global-offensive", name:"GLOBAL OFFENSIVE", img:"img/cards/soldiers-of-fortune/global-offensive.jpg", faction:["Bane"], vp:3, max:2 },
  { id:"cyber-attack", name:"CYBER ATTACK", img:"img/cards/soldiers-of-fortune/cyber-attack.jpg", faction:["Bane"], vp:2, max:2 },
  { id:"triangulation", name:"TRIANGULATION", img:"img/cards/soldiers-of-fortune/triangulation.jpg", faction:["Bane"], vp:2, max:3 },
  { id:"suppressing-fire", name:"SUPPRESSING FIRE", img:"img/cards/soldiers-of-fortune/suppressing-fire.jpg", faction:["Bane"], vp:2, max:3 },
  { id:"military-coordination", name:"MILITARY COORDINATION", img:"img/cards/soldiers-of-fortune/military-coordination.jpg", faction:["Bane"], vp:2, max:2 },
  { id:"enhanced-soldiers", name:"ENHANCED SOLDIERS", img:"img/cards/soldiers-of-fortune/enhanced-soldiers.jpg", faction:["Bane"], vp:2, max:3 },
  { id:"eradicate-the-order", name:"ERADICATE THE ORDER", img:"img/cards/league-of-assassins/eradicate-the-order.jpg", faction:["League of Shadows"], vp:3, max:3 },
  { id:"under-their-noses", name:"UNDER THEIR NOSES", img:"img/cards/league-of-assassins/under-their-noses.jpg", faction:["League of Shadows"], vp:2, max:4 },
  { id:"do-not-deviate-from-the-plan", name:"DO NOT DEVIATE FROM THE PLAN", img:"img/cards/league-of-assassins/do-not-deviate-from-the-plan.jpg", faction:["League of Shadows"], vp:2, max:3 },
  { id:"from-the-shadows", name:"FROM THE SHADOWS", img:"img/cards/league-of-assassins/from-the-shadows.jpg", faction:["League of Shadows"], vp:2, max:3 },
  { id:"blood-for-blood", name:"BLOOD FOR BLOOD", img:"img/cards/league-of-assassins/blood-for-blood.jpg", faction:["League of Shadows"], vp:2, max:2 },
  { id:"reclaim-the-lazarus-pit", name:"RECLAIM THE LAZARUS PIT", img:"img/cards/league-of-assassins/reclaim-the-lazarus-pit.jpg", faction:["League of Shadows"], vp:3, max:2 },
  { id:"we-cannot-be-defeated", name:"WE CANNOT BE DEFEATED", img:"img/cards/league-of-assassins/we-cannot-be-defeated.jpg", faction:["League of Shadows"], vp:2, max:2 },
  { id:"the-fire-rises", name:"THE FIRE RISES", img:"img/cards/league-of-assassins/the-fire-rises.jpg", faction:["League of Shadows"], vp:2, max:2 },
  { id:"multiple-threats", name:"MULTIPLE THREATS", img:"img/cards/league-of-assassins/multiple-threats.jpg", faction:["League of Shadows"], vp:3, max:3 },
  { id:"a-step-ahead", name:"A STEP AHEAD", img:"img/cards/league-of-assassins/a-step-ahead.jpg", faction:["League of Shadows"], vp:2, max:2 },
  { id:"where-ends-everything", name:"WHERE ENDS EVERYTHING", img:"img/cards/league-of-assassins/where-ends-everything.jpg", faction:["League of Shadows"], vp:2, max:3 },
  { id:"shadows-feint", name:"SHADOW'S FEINT", img:"img/cards/league-of-assassins/shadows-feint.jpg", faction:["League of Shadows"], vp:2, max:3 },
  { id:"well-rounded-mind", name:"WELL ROUNDED MIND", img:"img/cards/league-of-assassins/well-rounded-mind.jpg", faction:["League of Shadows"], vp:2, max:2 },
  { id:"smuggled-goods", name:"SMUGGLED GOODS", img:"img/cards/penguin/smuggled-goods.jpg", faction:["Penguin"], vp:3, max:3 },
  { id:"territory-fight", name:"TERRITORY FIGHT", img:"img/cards/penguin/territory-fight.jpg", faction:["Penguin"], vp:3, max:3 },
  { id:"this-is-mine", name:"THIS IS MINE!", img:"img/cards/penguin/this-is-mine.jpg", faction:["Penguin"], vp:2, max:4 },
  { id:"not-buying-dont-touch", name:"NOT BUYING? DON'T TOUCH!", img:"img/cards/penguin/not-buying-dont-touch.jpg", faction:["Penguin"], vp:2, max:3 },
  { id:"profitable-negotiation", name:"PROFITABLE NEGOTIATION", img:"img/cards/penguin/profitable-negotiation.jpg", faction:["Penguin"], vp:2, max:2 },
  { id:"secret-equipment-bases", name:"SECRET EQUIPMENT BASES", img:"img/cards/penguin/secret-equipment-bases.jpg", faction:["Penguin"], vp:2, max:2 },
  { id:"goods-raid", name:"GOODS RAID", img:"img/cards/penguin/goods-raid.jpg", faction:["Penguin"], vp:2, max:3 },
  { id:"everyone-has-a-price", name:"EVERYONE HAS A PRICE", img:"img/cards/penguin/everyone-has-a-price.jpg", faction:["Penguin"], vp:2, max:3 },
  { id:"unlimited-funds", name:"UNLIMITED FUNDS", img:"img/cards/penguin/unlimited-funds.jpg", faction:["Penguin"], vp:2, max:2 },
  { id:"get-it-fast", name:"GET IT, FAST!", img:"img/cards/penguin/get-it-fast.jpg", faction:["Penguin"], vp:2, max:3 },
  { id:"a-collector-of-goods", name:"A COLLECTOR OF GOODS", img:"img/cards/penguin/a-collector-of-goods.jpg", faction:["Penguin"], vp:2, max:2 },
  { id:"the-long-game", name:"THE LONG GAME", img:"img/cards/penguin/the-long-game.jpg", faction:["Penguin"], vp:2, max:4 },
  { id:"boo", name:"BOO!", img:"img/cards/scarecrow/boo.jpg", faction:["Scarecrow"], vp:2, max:4 },
  { id:"deepest-fears", name:"DEEPEST FEARS", img:"img/cards/scarecrow/deepest-fears.jpg", faction:["Scarecrow"], vp:2, max:4 },
  { id:"what-do-you-fear", name:"WHAT DO YOU FEAR?", img:"img/cards/scarecrow/what-do-you-fear.jpg", faction:["Scarecrow"], vp:3, max:3 },
  { id:"endless-torment", name:"ENDLESS TORMENT", img:"img/cards/scarecrow/endless-torment.jpg", faction:["Scarecrow"], vp:2, max:3 },
  { id:"fear-makes-you-predictable", name:"FEAR MAKES YOU PREDICTABLE", img:"img/cards/scarecrow/fear-makes-you-predictable.jpg", faction:["Scarecrow"], vp:2, max:3 },
  { id:"living-nightmare", name:"LIVING NIGHTMARE", img:"img/cards/scarecrow/living-nightmare.jpg", faction:["Scarecrow"], vp:2, max:2 },
  { id:"darkness-embrace", name:"DARKNESS' EMBRACE", img:"img/cards/scarecrow/darkness-embrace.jpg", faction:["Scarecrow"], vp:2, max:2 },
  { id:"its-ok-to-be-afraid", name:"IT'S OK TO BE AFRAID!", img:"img/cards/scarecrow/its-ok-to-be-afraid.jpg", faction:["Scarecrow"], vp:3, max:3 },
  { id:"intoxicated-by-fear", name:"INTOXICATED BY FEAR", img:"img/cards/scarecrow/intoxicated-by-fear.jpg", faction:["Scarecrow"], vp:2, max:2 },
  { id:"the-dawn-comes", name:"THE DAWN COMES", img:"img/cards/scarecrow/the-dawn-comes.jpg", faction:["Scarecrow"], vp:2, max:2 },
  { id:"test-patients", name:"TEST PATIENTS", img:"img/cards/scarecrow/test-patients.jpg", faction:["Scarecrow"], vp:2, max:3 },
  { id:"spooky-presence", name:"SPOOKY PRESENCE", img:"img/cards/scarecrow/spooky-presence.jpg", faction:["Scarecrow"], vp:2, max:3 },
  { id:"kill-them-twice", name:"KILL THEM TWICE", img:"img/cards/two-face/kill-them-twice.jpg", faction:["Two-Face"], vp:2, max:3 },
  { id:"two-make-this-better", name:"TWO MAKE THIS BETTER", img:"img/cards/two-face/two-make-this-better.jpg", faction:["Two-Face"], vp:2, max:3 },
  { id:"the-gamble", name:"THE GAMBLE", img:"img/cards/two-face/the-gamble.jpg", faction:["Two-Face"], vp:3, max:3 },
  { id:"heads-or-heads", name:"HEADS OR HEADS", img:"img/cards/two-face/heads-or-heads.jpg", faction:["Two-Face"], vp:2, max:3 },
  { id:"the-balance-of-justice", name:"THE BALANCE OF JUSTICE", img:"img/cards/two-face/the-balance-of-justice.jpg", faction:["Two-Face"], vp:2, max:2 },
  { id:"time-bomb", name:"TIME BOMB", img:"img/cards/two-face/time-bomb.jpg", faction:["Two-Face"], vp:3, max:3 },
  { id:"closing-argument", name:"CLOSING ARGUMENT", img:"img/cards/two-face/closing-argument.jpg", faction:["Two-Face"], vp:3, max:3 },
  { id:"two-faces-of-the-coin", name:"TWO FACES OF THE COIN", img:"img/cards/two-face/two-faces-of-the-coin.jpg", faction:["Two-Face"], vp:2, max:2 },
  { id:"double-or-nothing", name:"DOUBLE OR NOTHING", img:"img/cards/two-face/double-or-nothing.jpg", faction:["Two-Face"], vp:2, max:3 },
  { id:"fast-allegation", name:"FAST ALLEGATION", img:"img/cards/two-face/fast-allegation.jpg", faction:["Two-Face"], vp:2, max:4 },
  { id:"punishment", name:"PUNISHMENT", img:"img/cards/two-face/punishment.jpg", faction:["Two-Face"], vp:2, max:2 },
  { id:"the-odds", name:"THE ODDS", img:"img/cards/two-face/the-odds.jpg", faction:["Two-Face"], vp:2, max:3 },
  { id:"dark-multiverse-corruption", name:"DARK MULTIVERSE CORRUPTION", img:"img/cards/batman-who-laughs/dark-multiverse-corruption.jpg", faction:["Batman Who Laughs"], vp:2, max:3 },
  { id:"whispered-words", name:"WHISPERED WORDS", img:"img/cards/batman-who-laughs/whispered-words.jpg", faction:["Batman Who Laughs"], vp:2, max:4 },
  { id:"my-sons-kill", name:"MY SONS... KILL!", img:"img/cards/batman-who-laughs/my-sons-kill.jpg", faction:["Batman Who Laughs"], vp:2, max:4 },
  { id:"crow", name:"CROW", img:"img/cards/batman-who-laughs/crow.jpg", faction:["Batman Who Laughs"], vp:2, max:3 },
  { id:"something-twisted-and-wrong", name:"SOMETHING TWISTED AND WRONG", img:"img/cards/batman-who-laughs/something-twisted-and-wrong.jpg", faction:["Batman Who Laughs"], vp:2, max:3 },
  { id:"im-you", name:"I'M YOU", img:"img/cards/batman-who-laughs/im-you.jpg", faction:["Batman Who Laughs"], vp:2, max:3 },
  { id:"sleeper-agents", name:"SLEEPER AGENTS", img:"img/cards/batman-who-laughs/sleeper-agents.jpg", faction:["Batman Who Laughs"], vp:2, max:3 },
  { id:"big-cosmic-joke", name:"BIG COSMIC JOKE", img:"img/cards/batman-who-laughs/big-cosmic-joke.jpg", faction:["Batman Who Laughs"], vp:3, max:2 },
  { id:"a-world-that-shouldnt-exist", name:"A WORLD THAT SHOULDN'T EXIST", img:"img/cards/batman-who-laughs/a-world-that-shouldnt-exist.jpg", faction:["Batman Who Laughs"], vp:3, max:2 },
  { id:"lights-fault", name:"LIGHT'S FAULT", img:"img/cards/batman-who-laughs/lights-fault.jpg", faction:["Batman Who Laughs"], vp:2, max:2 },
  { id:"you-dont-trust-anything", name:"YOU DON'T TRUST ANYTHING", img:"img/cards/batman-who-laughs/you-dont-trust-anything.jpg", faction:["Batman Who Laughs"], vp:2, max:2 },
  { id:"take-a-good-look", name:"TAKE A GOOD LOOK", img:"img/cards/batman-who-laughs/take-a-good-look.jpg", faction:["Batman Who Laughs"], vp:2, max:3 },
  { id:"km-card-119", name:"Easy Riddle", img:"img/cards/official/119-easy-riddle.jpg", faction:["The Riddler"], vp:2, max:2 },
  { id:"km-card-121", name:"Riddle Me Softly", img:"img/cards/official/121-riddle-me-softly.jpg", faction:["The Riddler"], vp:2, max:2 },
  { id:"km-card-122", name:"Riddle Me That", img:"img/cards/official/122-riddle-me-that.jpg", faction:["The Riddler"], vp:3, max:3 },
  { id:"km-card-123", name:"Riddle Me This", img:"img/cards/official/123-riddle-me-this.jpg", faction:["The Riddler"], vp:3, max:3 },
  { id:"km-card-124", name:"Riddle of Nowhere", img:"img/cards/official/124-riddle-of-nowhere.jpg", faction:["The Riddler"], vp:2, max:4 },
  { id:"km-card-125", name:"Riddles on the Storm", img:"img/cards/official/125-riddles-on-the-storm.jpg", faction:["The Riddler"], vp:2, max:3 },
  { id:"km-card-126", name:"The Riddle of the Night", img:"img/cards/official/126-the-riddle-of-the-night.jpg", faction:["The Riddler"], vp:2, max:2 },
  { id:"km-card-127", name:"You Activate the Riddle", img:"img/cards/official/127-you-activate-the-riddle.jpg", faction:["The Riddler"], vp:2, max:3 },
  { id:"km-card-148", name:"Experimental Medication", img:"img/cards/official/148-experimental-medication.jpg", vp:0, max:1, reqModel:["Penny"], reqRank:["Henchman"] },
  { id:"km-card-173", name:"An Owl's Tale", img:"img/cards/official/173-an-owl-s-tale.jpg", faction:["Court of Owls"], vp:2, max:3 },
  { id:"km-card-174", name:"Gotham Is Ours", img:"img/cards/official/174-gotham-is-ours.jpg", faction:["Court of Owls"], vp:3, max:2 },
  { id:"km-card-175", name:"Owl's Night", img:"img/cards/official/175-owl-s-night.jpg", faction:["Court of Owls"], vp:3, max:2 },
  { id:"km-card-176", name:"Talon's Claw", img:"img/cards/official/176-talon-s-claw.jpg", faction:["Court of Owls"], vp:2, max:4 },
  { id:"km-card-177", name:"Terrible Accident", img:"img/cards/official/177-terrible-accident.jpg", faction:["Court of Owls"], vp:3, max:3 },
  { id:"km-card-178", name:"The Court's Secure Bases", img:"img/cards/official/178-the-court-s-secure-bases.jpg", faction:["Court of Owls"], vp:2, max:3 },
  { id:"km-card-179", name:"The Owl's Labyrinth", img:"img/cards/official/179-the-owl-s-labyrinth.jpg", faction:["Court of Owls"], vp:2, max:2 },
  { id:"km-card-180", name:"The Shadow Claw", img:"img/cards/official/180-the-shadow-claw.jpg", faction:["Court of Owls"], vp:2, max:4 },
  { id:"km-card-188", name:"Sacrifice", img:"img/cards/official/188-sacrifice.jpg", faction:["Cults"], vp:2, max:2 },
  { id:"km-card-189", name:"Ritual", img:"img/cards/official/189-ritual.jpg", faction:["Cults"], vp:3, max:3 },
  { id:"km-card-190", name:"New Followers", img:"img/cards/official/190-new-followers.jpg", faction:["Cults"], vp:2, max:2 },
  { id:"km-card-191", name:"Can be Anyone", img:"img/cards/official/191-can-be-anyone.jpg", faction:["Cults"], vp:2, max:2 },
  { id:"km-card-192", name:"Full Devotion", img:"img/cards/official/192-full-devotion.jpg", faction:["Cults"], vp:2, max:2 },
  { id:"km-card-193", name:"Awakening", img:"img/cards/official/193-awakening.jpg", faction:["Cults"], vp:2, max:3, reqRank:["Leader"], reqTrait:["Kobra Cultist"] },
  { id:"km-card-194", name:"Sabotage", img:"img/cards/official/194-sabotage.jpg", faction:["Cults"], vp:2, max:3, reqRank:["Leader"], reqTrait:["Kobra Cultist"] },
  { id:"km-card-195", name:"The Great Plan", img:"img/cards/official/195-the-great-plan.jpg", faction:["Cults"], vp:3, max:3, reqTrait:["Kobra Cultist"] },
  { id:"km-card-198", name:"Pinched Mobster", img:"img/cards/official/198-pinched-mobster.jpg", faction:["Organized Crime"], vp:3, max:3 },
  { id:"km-card-199", name:"Spring Cleaning", img:"img/cards/official/199-spring-cleaning.jpg", faction:["Organized Crime"], vp:2, max:3 },
  { id:"km-card-200", name:"Recovering the Juice", img:"img/cards/official/200-recovering-the-juice.jpg", faction:["Organized Crime"], vp:3, max:3 },
  { id:"km-card-201", name:"Paying Tribute", img:"img/cards/official/201-paying-tribute.jpg", faction:["Organized Crime"], vp:2, max:3 },
  { id:"km-card-202", name:"Message Job", img:"img/cards/official/202-message-job.jpg", faction:["Organized Crime"], vp:2, max:2 },
  { id:"km-card-203", name:"Killing the Rat", img:"img/cards/official/203-killing-the-rat.jpg", faction:["Organized Crime"], vp:2, max:2 },
  { id:"km-card-204", name:"The Program", img:"img/cards/official/204-the-program.jpg", faction:["Organized Crime"], vp:2, max:2 },
  { id:"km-card-205", name:"Shakedown", img:"img/cards/official/205-shakedown.jpg", faction:["Organized Crime"], vp:2, max:2 },
  { id:"km-card-221", name:"Important Research", img:"img/cards/official/221-important-research.jpg", faction:["Mr. Freeze"], vp:3, max:3 },
  { id:"km-card-222", name:"A Freeze is Coming", img:"img/cards/official/222-a-freeze-is-coming.jpg", faction:["Mr. Freeze"], vp:3, max:3 },
  { id:"km-card-223", name:"Stay Cool", img:"img/cards/official/223-stay-cool.jpg", faction:["Mr. Freeze"], vp:2, max:4 },
  { id:"km-card-224", name:"Chill Out", img:"img/cards/official/224-chill-out.jpg", faction:["Mr. Freeze"], vp:2, max:3 },
  { id:"km-card-225", name:"Frozen Assets", img:"img/cards/official/225-frozen-assets.jpg", faction:["Mr. Freeze"], vp:2, max:2 },
  { id:"km-card-226", name:"Endless Winter", img:"img/cards/official/226-endless-winter.jpg", faction:["Mr. Freeze"], vp:2, max:3 },
  { id:"km-card-227", name:"Kingdom of Ice", img:"img/cards/official/227-kingdom-of-ice.jpg", faction:["Mr. Freeze"], vp:2, max:3 },
  { id:"km-card-228", name:"Send them to the Cooler", img:"img/cards/official/228-send-them-to-the-cooler.jpg", faction:["Mr. Freeze"], vp:2, max:2 },
  { id:"km-card-243", name:"Let's Dance (Doom Patrol)", img:"img/cards/official/243-let-s-dance-doom-patrol.jpg", faction:["Doom Patrol"], vp:0, max:1 },
  { id:"km-card-244", name:"Psychopaths (Doom Patrol)", img:"img/cards/official/244-psychopaths-doom-patrol.jpg", faction:["Doom Patrol"], vp:0, max:3 },
  { id:"km-card-245", name:"Not Buying? Don't Touch (Doom Patrol)", img:"img/cards/official/245-not-buying-don-t-touch-doom-patrol.jpg", faction:["Doom Patrol"], vp:0, max:3 },
  { id:"km-card-246", name:"Riddles On The Storm (Doom Patrol)", img:"img/cards/official/246-riddles-on-the-storm-doom-patrol.jpg", faction:["Doom Patrol"], vp:0, max:3 },
  { id:"km-card-247", name:"We Cannot Be Defeated (Doom Patrol)", img:"img/cards/official/247-we-cannot-be-defeated-doom-patrol.jpg", faction:["Doom Patrol"], vp:0, max:2 },
  { id:"km-card-248", name:"I Work Best Alone (Doom Patrol)", img:"img/cards/official/248-i-work-best-alone-doom-patrol.jpg", faction:["Doom Patrol"], vp:0, max:2 },
  { id:"km-card-249", name:"Domination (Doom Patrol)", img:"img/cards/official/249-domination-doom-patrol.jpg", faction:["Doom Patrol"], vp:0, max:3 },
  { id:"km-card-250", name:"Let Them Do Their Thing (Doom Patrol)", img:"img/cards/official/250-let-them-do-their-thing-doom-patrol.jpg", faction:["Doom Patrol"], vp:0, max:1 },
  { id:"km-card-251", name:"Sisters In Arms (Doom Patrol)", img:"img/cards/official/251-sisters-in-arms-doom-patrol.jpg", faction:["Doom Patrol"], vp:0, max:2 },
  { id:"km-card-267", name:"Target Adquired", img:"img/cards/official/267-target-adquired.jpg", faction:["Suicide Squad"], vp:2, max:4 },
  { id:"km-card-268", name:"Revealing the Plan", img:"img/cards/official/268-revealing-the-plan.jpg", faction:["Suicide Squad"], vp:2, max:4 },
  { id:"km-card-269", name:"Subterfuge Mission", img:"img/cards/official/269-subterfuge-mission.jpg", faction:["Suicide Squad"], vp:2, max:3 },
  { id:"km-card-270", name:"Taking the Lead", img:"img/cards/official/270-taking-the-lead.jpg", faction:["Suicide Squad"], vp:2, max:3 },
  { id:"km-card-271", name:"Extermination Mission", img:"img/cards/official/271-extermination-mission.jpg", faction:["Suicide Squad"], vp:2, max:2 },
  { id:"km-card-272", name:"Risking All", img:"img/cards/official/272-risking-all.jpg", faction:["Suicide Squad"], vp:3, max:3 },
  { id:"km-card-273", name:"Interrogation Mission", img:"img/cards/official/273-interrogation-mission.jpg", faction:["Suicide Squad"], vp:2, max:3 },
  { id:"km-card-274", name:"A.R.G.U.S. Intelligence", img:"img/cards/official/274-a-r-g-u-s-intelligence.jpg", faction:["Suicide Squad"], vp:2, max:3 },
  { id:"km-card-275", name:"Behind the Enemy Line", img:"img/cards/official/275-behind-the-enemy-line.jpg", faction:["Suicide Squad"], vp:3, max:3 },
  { id:"km-card-276", name:"Who Watches the Watchmen?", img:"img/cards/official/276-who-watches-the-watchmen.jpg", faction:["Watchmen"], vp:2, max:3 },
  { id:"km-card-277", name:"Unneccessary Brutality", img:"img/cards/official/277-unneccessary-brutality.jpg", faction:["Watchmen"], vp:2, max:3 },
  { id:"km-card-278", name:"The Big Plan", img:"img/cards/official/278-the-big-plan.jpg", faction:["Watchmen"], vp:2, max:4 },
  { id:"km-card-279", name:"Retribution", img:"img/cards/official/279-retribution.jpg", faction:["Watchmen"], vp:2, max:2 },
  { id:"km-card-280", name:"Rorschach's Journal", img:"img/cards/official/280-rorschach-s-journal.jpg", faction:["Watchmen"], vp:2, max:3 },
  { id:"km-card-281", name:"Sealed Area", img:"img/cards/official/281-sealed-area.jpg", faction:["Watchmen"], vp:2, max:3 },
  { id:"km-card-282", name:"Day's Work", img:"img/cards/official/282-day-s-work.jpg", faction:["Watchmen"], vp:2, max:3 },
  { id:"km-card-283", name:"A Comedian Died", img:"img/cards/official/283-a-comedian-died.jpg", faction:["Watchmen"], vp:2, max:3 },
  { id:"km-card-308", name:"Where the Trail Ended", img:"img/cards/official/308-where-the-trail-ended.jpg", faction:["Cults"], vp:2, max:3, reqTrait:["Blackfire Cultist"] },
  { id:"km-card-309", name:"Tempted to Despair", img:"img/cards/official/309-tempted-to-despair.jpg", faction:["Cults"], vp:3, max:3, reqTrait:["Blackfire Cultist"] },
  { id:"km-card-310", name:"I See...", img:"img/cards/official/310-i-see.jpg", faction:["Cults"], vp:2, max:3, reqTrait:["Blackfire Cultist"] },
  { id:"km-card-330", name:"Ruthless Team", img:"img/cards/official/330-ruthless-team.jpg", faction:["Suicide Squad"], vp:2, max:2 },
  { id:"km-card-331", name:"Reinforcement Beacon Planted", img:"img/cards/official/331-reinforcement-beacon-planted.jpg", faction:["Suicide Squad"], vp:2, max:2 },
  { id:"km-card-332", name:"Misunderstood Orders", img:"img/cards/official/332-misunderstood-orders.jpg", faction:["Suicide Squad"], vp:3, max:2 },
  { id:"km-card-342", name:"Nuclear Menace", img:"img/cards/official/342-nuclear-menace.jpg", faction:["Watchmen"], vp:3, max:2 },
  { id:"km-card-343", name:"Soon it Will be Dark", img:"img/cards/official/343-soon-it-will-be-dark.jpg", faction:["Watchmen"], vp:2, max:2 },
  { id:"km-card-344", name:"Locked in Here with Me!", img:"img/cards/official/344-locked-in-here-with-me.jpg", faction:["Watchmen"], vp:2, max:2 },
  { id:"km-card-345", name:"Deceiving a God", img:"img/cards/official/345-deceiving-a-god.jpg", faction:["Watchmen"], vp:3, max:2 },
  { id:"km-card-346", name:"Pretending Normality", img:"img/cards/official/346-pretending-normality.jpg", faction:["Watchmen"], vp:2, max:2 },
  { id:"km-card-349", name:"Ace of Spades", img:"img/cards/official/349-ace-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-350", name:"Ace of Clubs", img:"img/cards/official/350-ace-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-351", name:"Ace of Diamonds", img:"img/cards/official/351-ace-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-352", name:"Ace of Hearts", img:"img/cards/official/352-ace-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-353", name:"Two of Spades", img:"img/cards/official/353-two-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-354", name:"Two of Clubs", img:"img/cards/official/354-two-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-355", name:"Two of Diamonds", img:"img/cards/official/355-two-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-356", name:"Two of Hearts", img:"img/cards/official/356-two-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-357", name:"Three of Spades", img:"img/cards/official/357-three-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-358", name:"Three of Clubs", img:"img/cards/official/358-three-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-359", name:"Three of Diamonds", img:"img/cards/official/359-three-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-360", name:"Three of Hearts", img:"img/cards/official/360-three-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-361", name:"Four of Spades", img:"img/cards/official/361-four-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-362", name:"Four of Clubs", img:"img/cards/official/362-four-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-363", name:"Four of Diamonds", img:"img/cards/official/363-four-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-364", name:"Four of Hearts", img:"img/cards/official/364-four-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-365", name:"Five of Spades", img:"img/cards/official/365-five-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-366", name:"Five of Clubs", img:"img/cards/official/366-five-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-367", name:"Five of Diamonds", img:"img/cards/official/367-five-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-368", name:"Five of Hearts", img:"img/cards/official/368-five-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-369", name:"Six of Spades", img:"img/cards/official/369-six-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-370", name:"Six of Clubs", img:"img/cards/official/370-six-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-371", name:"Six of Diamonds", img:"img/cards/official/371-six-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-372", name:"Six of Hearts", img:"img/cards/official/372-six-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-373", name:"Seven of Spades", img:"img/cards/official/373-seven-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-374", name:"Seven of Clubs", img:"img/cards/official/374-seven-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-375", name:"Seven of Diamonds", img:"img/cards/official/375-seven-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-376", name:"Seven of Hearts", img:"img/cards/official/376-seven-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-377", name:"Eight of Spades", img:"img/cards/official/377-eight-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-378", name:"Eight of Clubs", img:"img/cards/official/378-eight-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-379", name:"Eight of Diamonds", img:"img/cards/official/379-eight-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-380", name:"Eight of Hearts", img:"img/cards/official/380-eight-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-381", name:"Nine of Spades", img:"img/cards/official/381-nine-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-382", name:"Nine of Clubs", img:"img/cards/official/382-nine-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-383", name:"Nine of Diamonds", img:"img/cards/official/383-nine-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-384", name:"Nine of Hearts", img:"img/cards/official/384-nine-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-385", name:"Ten of Spades", img:"img/cards/official/385-ten-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-386", name:"Ten of Clubs", img:"img/cards/official/386-ten-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-387", name:"Ten of Diamonds", img:"img/cards/official/387-ten-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-388", name:"Ten of Hearts", img:"img/cards/official/388-ten-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-389", name:"Jack of Spades", img:"img/cards/official/389-jack-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-390", name:"Jack of Clubs", img:"img/cards/official/390-jack-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-391", name:"Jack of Diamonds", img:"img/cards/official/391-jack-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-392", name:"Jack of Hearts", img:"img/cards/official/392-jack-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-393", name:"Queen of Spades", img:"img/cards/official/393-queen-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-394", name:"Queen of Clubs", img:"img/cards/official/394-queen-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-395", name:"Queen of Diamonds", img:"img/cards/official/395-queen-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-396", name:"Queen of Hearts", img:"img/cards/official/396-queen-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-397", name:"King of Spades", img:"img/cards/official/397-king-of-spades.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-398", name:"King of Clubs", img:"img/cards/official/398-king-of-clubs.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-399", name:"King of Diamonds", img:"img/cards/official/399-king-of-diamonds.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-400", name:"King of Hearts", img:"img/cards/official/400-king-of-hearts.jpg", faction:["Royal Flush"], vp:1, max:1 },
  { id:"km-card-421", name:"Born to Riddle", img:"img/cards/official/421-born-to-riddle.jpg", faction:["The Riddler"], vp:2, max:3 },
  { id:"km-card-422", name:"Riddles of the World", img:"img/cards/official/422-riddles-of-the-world.jpg", faction:["The Riddler"], vp:2, max:3 },
  { id:"km-card-423", name:"Riddle Box Hero", img:"img/cards/official/423-riddle-box-hero.jpg", faction:["The Riddler"], vp:2, max:2 },
  { id:"km-card-424", name:"Psycho Riddle", img:"img/cards/official/424-psycho-riddle.jpg", faction:["The Riddler"], vp:2, max:4 },
  { id:"km-card-430", name:"The Primary Prey", img:"img/cards/official/430-the-primary-prey.jpg", faction:["Court of Owls"], vp:2, max:2 },
  { id:"km-card-431", name:"Stalking Parliament", img:"img/cards/official/431-stalking-parliament.jpg", faction:["Court of Owls"], vp:2, max:3 },
  { id:"km-card-432", name:"Not a Whispered Word", img:"img/cards/official/432-not-a-whispered-word.jpg", faction:["Court of Owls"], vp:2, max:3 },
  { id:"km-card-433", name:"Beware the Court of Owls", img:"img/cards/official/433-beware-the-court-of-owls.jpg", faction:["Court of Owls"], vp:2, max:3 },
  { id:"km-card-435", name:"The Inner Enemy", img:"img/cards/official/435-the-inner-enemy.jpg", faction:["Cults"], vp:2, max:2 },
  { id:"km-card-436", name:"Worship Place", img:"img/cards/official/436-worship-place.jpg", faction:["Cults"], vp:3, max:2 },
  { id:"km-card-437", name:"Prophecies of the Snake", img:"img/cards/official/437-prophecies-of-the-snake.jpg", faction:["Cults"], vp:2, max:3, reqTrait:["Kobra Cultist"] },
  { id:"km-card-438", name:"Followers of Kali-Yuga", img:"img/cards/official/438-followers-of-kali-yuga.jpg", faction:["Cults"], vp:2, max:3, reqTrait:["Kobra Cultist"] },
  { id:"km-card-439", name:"Eternal Life", img:"img/cards/official/439-eternal-life.jpg", faction:["Cults"], vp:2, max:3, reqTrait:["Blackfire Cultist"] },
  { id:"km-card-440", name:"A Godless City", img:"img/cards/official/440-a-godless-city.jpg", faction:["Cults"], vp:3, max:3, reqTrait:["Blackfire Cultist"] },
  { id:"km-card-443", name:"The Family", img:"img/cards/official/443-the-family.jpg", faction:["Organized Crime"], vp:2, max:3 },
  { id:"km-card-444", name:"Demonstration of Strength", img:"img/cards/official/444-demonstration-of-strength.jpg", faction:["Organized Crime"], vp:2, max:3 },
  { id:"km-card-445", name:"Vendetta", img:"img/cards/official/445-vendetta.jpg", faction:["Organized Crime"], vp:2, max:2 },
  { id:"km-card-446", name:"Dead Men Tell no Tales", img:"img/cards/official/446-dead-men-tell-no-tales.jpg", faction:["Organized Crime"], vp:2, max:3 },
  { id:"km-card-447", name:"Proof of Power", img:"img/cards/official/447-proof-of-power.jpg", faction:["Organized Crime"], vp:2, max:3 },
  { id:"km-card-456", name:"Harsh Conditions", img:"img/cards/official/456-harsh-conditions.jpg", faction:["Mr. Freeze"], vp:2, max:2 },
  { id:"km-card-457", name:"Technological Information", img:"img/cards/official/457-technological-information.jpg", faction:["Mr. Freeze"], vp:2, max:3 },
  { id:"km-card-458", name:"Cool Trophy", img:"img/cards/official/458-cool-trophy.jpg", faction:["Mr. Freeze"], vp:2, max:3 },
  { id:"km-card-459", name:"Hell Freezes Over", img:"img/cards/official/459-hell-freezes-over.jpg", faction:["Mr. Freeze"], vp:2, max:3 },
  { id:"attack-the-system", name:"ATTACK THE SYSTEM", img:"img/cards/harley-quinn-friends/attack-the-system.jpg", faction:["Birds of Prey"], vp:2, max:2 },
  { id:"fight-in-the-shadows", name:"FIGHT IN THE SHADOWS", img:"img/cards/harley-quinn-friends/fight-in-the-shadows.jpg", faction:["Birds of Prey"], vp:2, max:3 },
  { id:"blitzkrieg", name:"BLITZKRIEG", img:"img/cards/harley-quinn-friends/blitzkrieg.jpg", faction:["Birds of Prey"], vp:2, max:3 },
  { id:"riots-in-the-streets", name:"RIOTS IN THE STREETS", img:"img/cards/harley-quinn-friends/riots-in-the-streets.jpg", faction:["Birds of Prey"], vp:2, max:3 },
  { id:"match-day", name:"MATCH DAY", img:"img/cards/harley-quinn-friends/match-day.jpg", faction:["Birds of Prey"], vp:3, max:3 },
  { id:"the-revolt-has-begun", name:"THE REVOLT HAS BEGUN", img:"img/cards/harley-quinn-friends/the-revolt-has-begun.jpg", faction:["Birds of Prey"], vp:2, max:2 },
  { id:"selfie", name:"SELFIE!", img:"img/cards/harley-quinn-friends/selfie.jpg", faction:["Birds of Prey"], vp:2, max:3 },
  { id:"take-back-what-is-ours", name:"TAKE BACK WHAT IS OURS", img:"img/cards/harley-quinn-friends/take-back-what-is-ours.jpg", faction:["Birds of Prey"], vp:2, max:3 },
  { id:"ecoterrorism", name:"ECOTERRORISM", img:"img/cards/harley-quinn-friends/ecoterrorism.jpg", faction:["Birds of Prey"], vp:2, max:3 },
  { id:"outstanding-move", name:"OUTSTANDING MOVE", img:"img/cards/harley-quinn-friends/outstanding-move.jpg", faction:["Birds of Prey"], vp:2, max:3 },
  { id:"poison-the-supply", name:"POISON THE SUPPLY", img:"img/cards/harley-quinn-friends/poison-the-supply.jpg", faction:["Birds of Prey"], vp:2, max:2 },
  { id:"analog-hacking", name:"ANALOG HACKING", img:"img/cards/harley-quinn-friends/analog-hacking.jpg", faction:["Birds of Prey"], vp:2, max:4 }
];

const MANDATORY_CARDS = [
  { id:"vigilantes-special-rules", name:"VIGILANTES SPECIAL RULES", img:"img/cards/vigilantes/vigilantes-special-rules.jpg", faction:["Bat Family"] },
  { id:"harley-quinn-friends-special-rules", name:"HARLEY QUINN & FRIENDS SPECIAL RULES", img:"img/cards/harley-quinn-friends/harley-quinn-friends-special-rules.jpg", faction:["Birds of Prey"] },
  { id:"penguin-business-counters", name:"BUSINESS COUNTERS", img:"img/cards/penguin/business-counters-1.jpg", faction:["Penguin"] },
  { id:"penguin-business-counters-continued", name:"BUSINESS COUNTERS CONTINUED", img:"img/cards/penguin/business-counters-2.jpg", faction:["Penguin"] },
  { id:"scarecrow-the-fear", name:"THE FEAR", img:"img/cards/scarecrow/the-fear.jpg", faction:["Scarecrow"] },
  { id:"scarecrow-objective-cards-keywords", name:"OBJECTIVE CARDS KEYWORDS", img:"img/cards/scarecrow/objective-cards-keywords.jpg", faction:["Scarecrow"] },
  { id:"two-face-the-coin-good-side", name:"THE COIN GOOD SIDE", img:"img/cards/two-face/the-coin-good-side.png", faction:["Two-Face"] },
  { id:"two-face-the-coin-twisted-side", name:"THE COIN TWISTED SIDE", img:"img/cards/two-face/the-coin-twisted-side.jpg", faction:["Two-Face"] },
  { id:"batman-who-laughs-special-rules", name:"BWL SPECIAL RULES", img:"img/cards/batman-who-laughs/bwl-special-rules.jpg", faction:["Batman Who Laughs"] },
  { id:"km-card-231", name:"Ice Age", img:"img/cards/official/231-ice-age.jpg", faction:["Mr. Freeze"] },
  { id:"km-card-232", name:"Frozen", img:"img/cards/official/232-frozen.jpg", faction:["Mr. Freeze"] },
  { id:"km-card-333", name:"Cranial Bomb Activated", img:"img/cards/official/333-cranial-bomb-activated.jpg", faction:["Suicide Squad"] },
  { id:"km-card-334", name:"Suicide Squad Special Rules", img:"img/cards/official/334-suicide-squad-special-rules.jpg", faction:["Suicide Squad"] },
  { id:"km-card-347", name:"Watchmen Special Rules", img:"img/cards/official/347-watchmen-special-rules.jpg", faction:["Watchmen"] },
  { id:"km-card-348", name:"Royal Flush Gang Special Rules", img:"img/cards/official/348-royal-flush-gang-special-rules.jpg", faction:["Royal Flush"] },
  { id:"km-card-434", name:"Owl Markers Rules", img:"img/cards/official/434-owl-markers-rules.jpg", faction:["Court of Owls"] },
  { id:"km-card-441", name:"Faith Rules 1", img:"img/cards/official/441-faith-rules-1.jpg", faction:["Cults"] },
  { id:"km-card-442", name:"Faith Rules 2", img:"img/cards/official/442-faith-rules-2.jpg", faction:["Cults"] },
  { id:"km-card-448", name:"Black Market Rules", img:"img/cards/official/448-black-market-rules.jpg", faction:["Organized Crime"] },
  { id:"km-card-449", name:"Black Market Equipment", img:"img/cards/official/449-black-market-equipment.jpg", faction:["Organized Crime"] }
];
